# Generated by Django 3.2.15 on 2022-09-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20220913_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
