# Generated by Django 3.2.15 on 2022-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20220914_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_subject',
            field=models.BooleanField(null=True),
        ),
    ]
