# Generated by Django 3.2.15 on 2022-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_tag_is_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_subject',
            field=models.BooleanField(default=False),
        ),
    ]
