# Generated by Django 3.2.15 on 2022-10-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_auto_20221003_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
